### PR TITLE
feat: Be usable non-ladle query params

### PR DESCRIPTION
**Pull request by cm-dyoshikawa**
https://github.com/tajo/ladle/issues/496

### CODE REVIEW

**Comment by tajo** [comment]
Can you please move [packages/example/src/query-parameters.stories.tsx](https://github.com/tajo/ladle/pull/506/files#diff-222ff5eb6953644c60e3da26b8933d590520e5bed009a116b54324a4b25a751f) to https://github.com/tajo/ladle/tree/main/e2e/addons/src and create an e2e test for this feature?

**Comment by dyoshikawa** [comment]
@tajo Thanks for your review. OK, I'll work on it.

**Comment by cm-dyoshikawa** [comment]
Thanks for your review. OK, I'll work on it.

**Comment by cm-dyoshikawa** [comment]
@tajo I've written the e2e tests. Could you review again?

**Comment by tajo** [comment]
> @tajo I've written the e2e tests. Could you review again?

Nice. You should one more step, for example, click on RTL button and then assert that the custom query param still exists.

I suspect the current e2e test would work even without this PR.

**Comment by cm-dyoshikawa** [comment]
@tajo Than you for your check.

Is the RTL button right side menu story link button?

**Comment by cm-dyoshikawa** [comment]
@tajo I fixed and added the test case. Could you check again?

**Comment by tajo** [comment]
I think changing stories should actually remove these user query params. We do the same for Ladle query params. It doesn't make sense to "bring over" things like control state to unrelated stories / components. I would always assume the same for user query params as well. Stories should work in isolation.

So this is actually a great test that you have added but it should check the opposite result - removing these query params.

And then you should add an additional test that's changing something like RTL or theme state and checking that these user query params get preserved.

**Comment by cm-dyoshikawa** [comment]
@tajo 

Thank you for your comment.

> So this is actually a great test that you have added but it should check the opposite result - removing these query params.

OK, I've largely understood this.

> And then you should add an additional test that's changing something like RTL or theme state and checking that these user query params get preserved.

I'm sorry, what does RTL stand for?

**Comment by tajo** [comment]
> I'm sorry, what does RTL stand for?

Right-to-left, one of the bottom left addons.

**Comment by cm-dyoshikawa** [comment]
@tajo 

> I think changing stories should actually remove these user query params. We do the same for Ladle query params. It doesn't make sense to "bring over" things like control state to unrelated stories / components. I would always assume the same for user query params as well. Stories should work in isolation.

Do you have any ideas to make this happen?
If `modifyParams` runs before each Story's `useEffect`, then we can first clear all user query params with `modifyParams`, and then let the Story's `useEffect` handle the operation of query params. However, in reality, `modifyParams` seems to be executed after each Story's `useEffect`.
To resolve this, I still think it would be good to be able to inject query params as a meta element of the Story.

**Comment by tajo** [comment]
I think it can be done here: https://github.com/tajo/ladle/blob/main/packages/ladle/lib/app/src/app.tsx#L183

**Comment by dyoshikawa** [comment]
Thank you. I will check it.

**Pull request merged**
