### PR TITLE
fix: import performance explicitly

### LINKED ISSUE #221: ReferenceError: performance is not defined
**Describe the bug**

Works locally, but getting the following error in CI:

> ReferenceError: performance is not defined

```yml
  ladle-build:
    needs: install
    runs-on: ubuntu-latest
    name: Ladle Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install NPM 8
        run: npm install -g npm@8

      - name: Install
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: npm ci

      - name: Build Ladle
        run: npx ladle build
```

**Environment**

 - OS: linux
 - Browser N/A
 - Version `"@ladle/react": "2.1.0",`

### PR DESCRIPTION
**Pull request by moltar**
Closes #221

### CODE REVIEW

**Comment by tajo** [comment]
I am fine to merge this but we are not going to actively support Node 14.

**Comment by moltar** [comment]
Thank you for the feedback?

Any particular reason for not supporting 14?

I think it's still quite a popular version in the wild.

**Comment by moltar** [comment]
Also if you do indeed feel strongly about not supporting 14, perhaps add it to the docs and maybe even in the engine section of package.json. That way it's more clear and users know what to expect. Thank you.

**Comment by tajo** [comment]
It's in the root: https://github.com/tajo/ladle/blob/main/package.json#L57 but we should add it to the package itself as well.

**Pull request merged**
