### PR TITLE
Support ExportSpecifier defined stories

### PR DESCRIPTION
**Pull request by i-am-the-slime**
This is in response to #554 

In my local testing it works, however it only works for the first story in the export list, is this what we want?
Otherwise I could probably loop but the code would be a bit more involved.

### CODE REVIEW

**Comment by tajo** [comment]
> In my local testing it works, however it only works for the first story in the export list, is this what we want?

It should definitely work for multiple stories/specifiers. Also, tests need to be added.

[This](https://astexplorer.net/#/gist/7dc7f4231e3e33e03e3d0e7ca4a2c8a5/fd7153d6ad70cd7dfa5fefd0c84f0dd79257a05b) is an interesting case:

```js
const joe = 'joe';

export { joe, joe as jim }
```

Should parse out`joe` and `jim`

**Comment by i-am-the-slime** [comment]
@tajo 

It now parses all stories in the block (including those with a reexported name) and there's a test for it. 
It doesn't resolve the original AST node of what's being exported so it misses the "function/class/variable" check.
I hope that's okay.

**Comment by i-am-the-slime** [comment]
@tajo Could you have another look, please?

**Comment by tajo** [comment]
lgtm

**Comment by i-am-the-slime** [comment]
lgtmt

**Pull request merged**
