### PR TITLE
feat: ✨ prefix data-themes with "ladle"

### PR DESCRIPTION
**Pull request by melMass**
Addresses #304 

To avoid clashes in projects/components
that might already rely on data-theme.

`light` is not explicitly used in styling though
It's just `not dark`

~~I did it quickly just to see if it solved my issue, it does, but maybe the cli/configs etc.. should still use `dark` & `light` and only add the prefix in the method that alters the data-theme (will address it as soon as I have more time...)~~ I reverted the commit and did it

### CODE REVIEW

**Comment by melMass** [comment]
@tajo Wouldn't it make sense to explicitly use `[data-theme="ladle-light"]` too?

**Comment by its-monotype** [comment]
> Addresses #304 
> 
> To avoid clashes in projects/components
> that might already rely on data-theme.
> 
> `light` is not explicitly used in styling though
> It's just `not dark`
> 
> ~~I did it quickly just to see if it solved my issue, it does, but maybe the cli/configs etc.. should still use `dark` & `light` and only add the prefix in the method that alters the data-theme (will address it as soon as I have more time...)~~ I reverted the commit and did it

But it will note break dark theme for own components cause tailwind use data-theme and not ladle?

**Comment by melMass** [comment]
> But it will note break dark theme for own components cause tailwind use data-theme and not ladle?

What do you mean? (I don't use TW)

**Comment by tajo** [comment]
As I mentioned in #304, it makes sense to me to use

```
data-ladle-theme=light
data-ladle-theme=dark
```

so there is no clash with other systems/CSS using `data-theme`. This change doesn't really address that?

**Pull request closed without merging**
