### PR TITLE
feat(devcontainer): add devcontainer config files

### PR DESCRIPTION
**Pull request by andrewbrey**
Provide the ability to work on this project inside of a Docker container and/or on GitHub Codespaces through the creation of `devcontainer` and `Docker` configuration files.

This helps contributors to all share the same development environment, notably, ensuring that everyone uses the same versions of the various tools required for development of Ladle. Further, it makes it possible to work on the project without the need to install this project's tools and dependencies globally on your computer.

The configurations build upon the official `Playwright` Docker images (and security profiles) to ensure contributors have everything they need to run development, testing, linting, and building processes.

### CODE REVIEW

**Comment by tajo** [comment]
It seems that Ladle can't connect to the HMR server through the port `24678`. It is correctly auto-forwarded according to the UI but keeps hanging in the application.

Tested in `packages/example` with `pnpm ladle serve`

Any idea what could be wrong?

**Comment by andrewbrey** [comment]
> It seems that Ladle can't connect to the HMR server through the port 24678. It is correctly auto-forwarded according to the UI but keeps hanging in the application.

@tajo I'm not sure :thinking: - I have some time tonight so I can look at it. I wonder if there just needs to be a port added to the devcontainer configuration or something. I also wonder if this behaves differently on codespace vs local devcontainer.... I'll update once I've had a chance to poke at it :+1:

**Comment by andrewbrey** [comment]
@tajo I played around with this, and I'm going to bet that you did your testing on a GitHub Codespace. I tried that also, and found that Vite HMR "works" inside of the codespace, but it takes a very long time for changes to reflect, so long that it seems it ends up doing a full page refresh. I _suspect_ that the "hanging" is a `vite` devserver websocket message timeout, but that is more or less a minimally educated guess. If I were going to take a stab at explaining a root cause for the websocket "HMR" message timeout, I would bet it's CORS, since on a codespace, your preview origin and your codespace origin are different...this is just a guess, but I would not be surprised to learn this is the cause.

It's possible some fiddling with the packages `vite` devserver configuration might fix it (the server configuration for `vite` does have some CORS configuration https://vitejs.dev/config/#server-cors options). 

_Fortunately_ the overall feature of "when I change the source files, `Ladle` should update" _does take place_, so it's got a (slightly cumbersome) workaround.

Good new though! I also confirmed that when you use the `Remote - Containers` extension of `vscode` to use the devcontainer locally (via Docker), that HMR works as expected!

Here are some videos showing the results of my testing:

**Codespace**

https://user-images.githubusercontent.com/34140052/178178363-36ad4c9f-27b2-4c5b-ab1f-08322c413be4.mp4

**Local**

https://user-images.githubusercontent.com/34140052/178178408-0d6e0adb-d165-4230-b468-3bb9515d9764.mp4

**Comment by tajo** [comment]
Yea, I observed this problem with Github Codespace.

**Pull request merged**
