### PR TITLE
Fix iframe positioning when its wider than the <main />

### LINKED ISSUE #314: Setting large viewport in a small browser window causes iframe to shrink and doesn't produce scrollbars
**Describe the bug**

Setting large viewport in a small browser window doesn't produce scrollbars.

**Reproduction**

* Choose story viewport: large (1024px)
* Make your browser window small enough, e.g. 800px
* Observe how the viewport you selected shrinks

**How to fix**
 
* Make sure to set min-width equal to `width` on the iframe to prevent it from shrinking when placed in a smaller viewport
* Change `.ladle-main` styles not to center the iframe when it doesn't fit inside; currently `display: flex;
    justify-content: center;` causes the iframe to be partially hidden even with the fix mentioned above applied. Instead, center the iframe using `margin: 64px auto` set on the iframe.

### PR DESCRIPTION
**Pull request by tajo**
fixes #314

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Ummm... I don't think this looks how it's supposed to:

image

**Comment by tajo** [comment]
A repro? What browser?

**Comment by wojtekmaj** [comment]
Just plain Chrome 🤷‍♂️ I can reproduce this consistently on Edge and Firefox as well. I can reproduce it consistently across multiple projects.

Looking at the code, you specifically set .ladle-main to `grid-template-columns: minmax(64px, 1fr) auto minmax(64px, 1fr);` which, AT BEST, will land you 64px margins on both sides.

With `grid-template-columns: minmax(0, 64px) auto minmax(0, 64px);`, I'm getting 64px margins unless I make the screen so small the content in the middle no longer fits and the outer columns have to shrink.

Here's repro, but it's stupid simple, just a button, nothing more:

[ladle.zip](https://github.com/tajo/ladle/files/11293104/ladle.zip)

Here's a built repro (use npx serve to serve it):

[build.zip](https://github.com/tajo/ladle/files/11293102/build.zip)

**Comment by tajo** [comment]
`2.12.2` should fix this.

I was testing styles for set `width` not just `iframed: true` (they need to be handled differently).

**Pull request merged**
