### PR TITLE
Add expandStoryTree config option

### PR DESCRIPTION
**Pull request by jozefhruska**
This PR adds a new `expandStoryTree` config option. So far, it's undocumented, as I saw that the options added in #427 are also not documented, but I'll gladly update the documentation if necessary.

Related to #423.

### CODE REVIEW

**Comment by tajo** [comment]
It would be nice to also implement this https://github.com/tajo/ladle/issues/422 since that would greatly cut the length of expanded navigation.

**Comment by jozefhruska** [comment]
> It would be nice to also implement this #422 since that would greatly cut the length of expanded navigation.

Definitely! Would you like it to be a part of this PR or a separate one?

**Comment by tajo** [comment]
> Would you like it to be a part of this PR or a separate one?

Probably as a part of this PR since this mostly just renames a few things / changes config but having single story files being "hoisted" would make this feature very practical.

**Comment by tajo** [comment]
Actually, changed my mind on https://github.com/tajo/ladle/issues/422 

so this can be landed as is

**Comment by tajo** [comment]
Feel free to reopen after resolving conflicts/documenting.

**Pull request closed without merging**
