### PR TITLE
Restrict install to node >= v16

### PR DESCRIPTION
**Pull request by GeorgeNagel**
After adding an `engines` config and .npmrc file, install with old versions of node fails 🥳 

Related to [this issue](https://github.com/tajo/ladle/issues/169)

[Related npm docs on engine-strict](https://docs.npmjs.com/cli/v8/using-npm/config#engine-strict)

Output when trying to install on an old version of node:
```
$ npm install
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm ERR! code ENOTSUP
npm ERR! prepareGitDep npm ERR! notsup Unsupported engine for ladle@0.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"12.13.0","npm":"6.12.0"})
npm ERR! prepareGitDep npm ERR! notsup Not compatible with your version of node/npm: ladle@0.0.0
npm ERR! prepareGitDep npm ERR! notsup Not compatible with your version of node/npm: ladle@0.0.0
npm ERR! prepareGitDep npm ERR! notsup Required: {"node":">=16.0.0"}
npm ERR! prepareGitDep npm ERR! notsup Actual:   {"npm":"6.12.0","node":"12.13.0"}
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     <some-path>/.npm/_logs/2022-06-22T17_45_14_735Z-debug.log
npm ERR! prepareGitDep
npm WARN foodle@1.0.0 No description
npm WARN foodle@1.0.0 No repository field.

npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     <some-path>/.npm/_logs/2022-06-22T17_45_14_842Z-debug.log
```

### CODE REVIEW

**Comment by GeorgeNagel** [comment]
Figuring out the changeset thing...

**Comment by tajo** [comment]
Thanks! I was just about to add it since a few people struggled with Ladle and Node 14 recently.

**Comment by GeorgeNagel** [comment]
> Actually, this is good for users of this monorepo but we should add engines into the `packages/ladle/package.json` as well?

Maybe? I'm not sure what context people would be working within just that package.

A `pnpm install` at the top-level folder _or_ within `packages/ladle` gives me the same warning after this PR was merged:

```
$ pwd
<some-path>/ladle/packages/ladle

$ pnpm install
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your Node version is incompatible with "<some-path>/ladle".

Expected version: >=16.0.0
Got: v12.13.0

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
```

**Comment by tajo** [comment]
I was thinking about users of `@ladle/react`, they install ladle and it doesn't work for them because they are on node v14 without seeing some reasonable error message.

**Comment by GeorgeNagel** [comment]
Do you mean people that install `@ladle/react` as a dependency of their project?
I get the same failure message as the one in the description of this PR when installing ladle from my branch:

```
$ mkdir my-ladle
$ cd my-ladle
$ npm init --yes
$ npm install "https://github.com/GeorgeNagel/ladle.git#feature/node-16-readme"

npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm ERR! code ENOTSUP
npm ERR! prepareGitDep npm ERR! notsup Unsupported engine for ladle@0.0.0: wanted: {"node":">=16.0.0"} (current: {"node":"12.13.0","npm":"6.12.0"})
npm ERR! prepareGitDep npm ERR! notsup Not compatible with your version of node/npm: ladle@0.0.0
npm ERR! prepareGitDep npm ERR! notsup Not compatible with your version of node/npm: ladle@0.0.0
npm ERR! prepareGitDep npm ERR! notsup Required: {"node":">=16.0.0"}
npm ERR! prepareGitDep npm ERR! notsup Actual:   {"npm":"6.12.0","node":"12.13.0"}
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!    <some-path>/.npm/_logs/2022-06-23T21_04_06_879Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     <some-path>/.npm/_logs/2022-06-23T21_04_06_938Z-debug.log
```
I'm assuming that future users will receive the same message when a build containing the changes from this branch is published to npm. Or shoud `npm install @ladle/react` be failing for me aready on node 12x?

**Comment by tajo** [comment]
> I get the same failure message as the one in the description of this PR when installing ladle from my branch

Is that really installing `@ladle/react`?

This PR updates only the root level `package.json`, not `@ladle/react`'s `package.json`.

**Comment by GeorgeNagel** [comment]
Got it. Thanks for your patience. I don't know of a way to test that with a git repo to validate the change, but I'm happy to put up the PR.

**Pull request merged**
